- cspell.json
- src/connection-state-handler.spec.ts
- src/connection-state-handler.ts
- src/event-emitter.ts
- src/media/local-track.ts
- src/mocks/mock.ts
- src/mocks/rtc-peer-connection-stub.ts
- src/peer-connection-utils.ts
- src/peer-connection.spec.ts
- src/peer-connection.ts
Added connection state handler that takes ice connection state and dtls connection state and calculates the final overall state from these two.
Also fixed various warnings that I've found are currently on master.
> feat: added connection state handling

- src/peer-connection.ts
Added export for ConnectionState that was missed in https://github.com/webex/webrtc-core/pull/8
> fix: added export for ConnectionState

- src/peer-connection.ts
This PR adds a getStats method to the PeerConnection class.
> feat: add getStats to PeerConnection

- src/media/local-track.ts
When disposing all effects attached to a track, we need to restore the underlying stream to the original stream.
> fix: restore the original stream on disposing effects

- src/mocks/rtc-peer-connection-stub.ts
- src/peer-connection.spec.ts
- src/peer-connection.ts
API for fetching the the connection type, which would return the type of Promise<'UDP' | 'TCP' | 'TURN-TLS' | 'TURN-TCP' | 'TURN-UDP' | 'unknown'>. 
Details can refer to https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-379327
> feat: add the api for fetching the connection type

- samples/src/App.js
When I ran `yarn start` I found these three functions can not be found, think they are discarded due to rollup tree-shaking. In opposite, `bundle` includes all exported functions. It won't throw function not found error if we use `bundle`.
> chore: Import media sdk from bundle

- src/device/device-management.ts
- src/media/local-track.spec.ts
- src/media/local-track.ts
- src/mocks/media-stream-track-stub.ts
- src/util/test-utils.ts
This PR adds the necessary constraints and methods to support music mode on local audio tracks.
It adds the following APIs to LocalTrack:
- `applyConstraints`: useful for applying music mode constraints to the track, though [it doesn't work for audio constraints on Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=796964); still, I think it'll be useful for other browsers like Firefox, so that it doesn't need to make a new call to `getUserMedia`.
- `getConstraints`: not strictly necessary for music mode but useful for testing purposes.
- `getSettings`: as far as I know, this is the recommended way to get the device ID of the track, useful for calling `getUserMedia` again on Chrome.
> feat: support applying music mode constraints

- src/media/local-track.spec.ts
- src/media/local-track.ts
- src/mocks/media-stream-track-stub.ts
- src/util/test-utils.ts
This code changes merged the PR of Bryce's [support applying music mode constraints](https://github.com/webex/webrtc-core/pull/27/files)
Mainly changes: 
1.  Add an event to LocalTrack for when the constraints are called
2. Add a method named getNumActiveSimulcastLayers to check the resolution and return how many layers will be active
> feat: Method named getNumActiveSimulcastLayers & event to LocalTrack for constraints changed

- src/device/device-management.spec.ts
- src/device/device-management.ts
To allow JS-SDK to have classes that extend webrtc-core LocalMicrophoneTrack, LocalCameraTrack etc.
> fix: made create*Track() functions generic

- .github/workflows/npm-publish.yml
this attempts to point the workflow file at a token that will allow semantic release to push to the branch even with branch protections enabled.
> fix: fix workflow token

- src/connection-state-handler.ts
noticed this when debugging something else.  it results in very confusing log messages like:
```
[webrtc-core] iceConnectionState=connected connectionState=connected => Connecting
```
think it was just a typo.
> fix: incorrect log

- package.json
- src/media/local-stream.spec.ts
- src/media/local-stream.ts
- yarn.lock
Start of the effects API.  Right now it requires `BaseEffect` from `@webex/web-media-effects` which brings in quite a few dependencies that we probably don't want.
> feat: effects api

- src/device/device-management.ts
- src/index.ts
- src/media/local-system-audio-track.ts
This PR adds a new track class (`LocalSystemAudioTrack`) and a new API for getting slides audio (`createDisplayTrackWithAudio`).
Considered naming the track class `LocalDisplayAudioTrack` or `LocalSystemTrack`, ended up using a combination of both.
> feat: add support for getting slides audio

- src/device/device-management.ts
This PR updates `createDisplayTrackWithAudio` to resolve the audio track as `null` if it is not available (i.e. the user unchecks the share audio option when selecting content to share in Chrome). This fix is necessary because `LocalTrack` expects at least one track to exist in the media stream when created.
> fix: resolve system audio as null if unavailable

- src/device/device-management.spec.ts
- src/media/local-stream.spec.ts
- src/media/local-stream.ts
- src/media/remote-stream.spec.ts
- src/media/remote-stream.ts
- src/media/stream.ts
- src/mocks/media-stream-stub.ts
- src/mocks/media-stream-track-stub.ts
This PR makes several additional changes to the stream classes, including listening to media stream track events in `Stream`, adding more abstract methods, and updating how `inputTrack` and `outputTrack` are used in `LocalStream`.
> feat: listen to track events and additional updates to stream classes

- src/device/device-management.spec.ts
- src/device/device-management.ts
This PR adds generics to device management `create*Stream` functions in order to support using custom stream classes in these methods. It also adds a new API, `createCameraAndMicrophoneStreams`, to create both a camera stream and a microphone stream with a single `getUserMedia` call.
As part of this change, I've also slightly modified the `ErrorTypes` to have a generic `CREATE_STREAM_FAILED` error so it can be used in all cases in which `getUserMedia` or `getDisplayMedia` fail.
This completes [SPARK-448441](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-448441) and [SPARK-448443](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-448443).
> feat: add generics to device management

- package.json
- src/mocks/rtc-peer-connection-stub.ts
- src/peer-connection.spec.ts
- src/peer-connection.ts
- yarn.lock
This PR fixes an issue in which Firefox will allow `setLocalDescription` to be called even when all the codecs have been removed from the media line as part of [SPARK-465378](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-465378). This violates RFC8866, which states that at least one codec is required.
A bug has been filed to Firefox about this: https://bugzilla.mozilla.org/show_bug.cgi?id=1857612
Until Firefox fixes this bug, the fix from our end is to add a check in `setLocalDescription` to check the number of fields in the media line. This is similar to what Google does: https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/pc/webrtc_sdp.cc;l=2682;drc=f5bdc89c7395ed24f1b8d196a3bdd6232d5bf771
If the number of fields is less than 4 (i.e. the codecs are missing), …
> fix: throw error in setLocalDescription if media line is missing codecs

- src/device/device-management.ts
- src/errors.ts
- src/index.ts
This PR renames `WcmeError` to `WebrtcCoreError`, and moves the error object to its own file, as part of [WEBEX-365025](https://jira-eng-gpk2.cisco.com/jira/browse/WEBEX-365025).
> fix: rename WcmeError to WebrtcCoreError

- src/device/device-management.ts
- src/errors.ts
This PR renames the error type enum from `WebrtcCoreErrorTypes` to `WebrtcCoreErrorType` to keep it consistent with the changes being made in WCME.
> fix: rename error type enum

- src/peer-connection.ts
This PR fixes the case in which an invalid m-line with a trailing whitespace may be considered to be valid. For example, "m=video 9 UDP/TLS/RTP/SAVPF " should be throwing an error, but the trailing space causes webrtc-core to think it is valid.
> fix: handle invalid m-line with trailing whitespace

- src/media/local-stream.spec.ts
- src/media/local-stream.ts
- src/media/stream.ts
This PR also checks the mute property of the track when calling `LocalStream.muted`. This more accurately reflects the mute state of the track; for example, when sharing a window, the track gets muted by the browser when the shared window is minimized.
> fix: check muted property for mute getter

- src/media/local-stream.spec.ts
- src/media/local-stream.ts
The main purpose of this update is to make better work with LocalStream and smoother debugging for [webex-js-sdk](https://github.com/webex/webex-js-sdk). Mainly it should get rid of custom overrides for objects and give more useful information in better structure. See current overrides here https://github.com/webex/webex-js-sdk/pull/3148/commits/4089648179ee2566cab1e7e718c6ac5908c83eb7
This PR consists of the following updates: 
- update for `_LocalStream` object and add custom `toJSON` method
- added new test cases for `_LocalStream`
> feat: add custom method toJSON for _LocalStream

- cspell.json
- package.json
- src/mocks/rtc-peer-connection-stub.ts
- src/peer-connection.spec.ts
- src/peer-connection.ts
Added events that will be called on success operations on offer/answer/description
This includes
- `CreateOfferOnSuccess` - when `createOffer` succeeded
- `CreateAnswerOnSuccess` - when `createAnswer` succeeded
- `SetLocalDescriptionOnSuccess` - when `setLocalDescription` succeeded
- `SetRemoteDescriptionOnSuccess` - when `setRemoteDescription` succeeded
> feat: set/create events

- src/media/local-stream.spec.ts
- src/media/local-stream.ts
- src/media/local-video-stream.spec.ts
- src/media/remote-stream.spec.ts
- src/media/remote-stream.ts
- src/media/stream.ts
This PR updates the mute events and getters to make it clear whether the user muted the stream or the system muted the stream as part of [SPARK-493485](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-493485). The main changes are:
`Stream`:
- Remove event `MuteStateChange`. This will be replaced with new events in `LocalStream`/`RemoteStream`.
`LocalStream`:
- Add event `UserMuteStateChange`, emits a boolean with the new user mute state.
- Add event `SystemMuteStateChange`, emits a boolean with the new system mute state.
- Getters `userMuted`/`systemMuted`
- `muted` will be in `LocalStream` only, gets the overall mute state (taking into consideration both `userMuted` and `systemMuted`)
`RemoteStream`:
- Add event `MediaStateChange`, emits either "started" or "stopped".
- Remove getter …
> feat: separate API for enabled and muted states

- src/media/local-stream.ts
This PR simply disposes any effects added to the `LocalStream` when `LocalStream.stop` is called. It is being done as part of https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-515171.
It is reasonable to expect that once a stream has been stopped, its effects should be disposed. Not disposing the effects means using up computing resources on effects that are no longer used. A common example is switching camera devices while VBG is enabled, which would stop the old track and add a new effect on the new track.
> fix: dispose effects on call to LocalStream.stop

- src/peer-connection.ts
This PR exposes an additional event which will allow listening on generated ICE Candidates. 
`PeerConnection`:
* Add event `IceCandidate`, emits a `RTCPeerConnectionIceEvent` with gathered ICE Candidate Event
This change is provided to allow keeping track of generated ICE Candidates. Currently, it will be used to check if Firefox has properly generated relay candidate due to the existing bug -> https://bugzilla.mozilla.org/show_bug.cgi?id=1891503.
> feat: expose on ice candidate event callback

- src/peer-connection.ts
This PR exposes `ConnectionType` type,
It's a missing part to be able to use getCurrentConnectionType comfortably.
> feat: expose ConnectionType for easier usage of getCurrentConnectionType

- package.json
- src/device/device-management.spec.ts
- src/device/device-management.ts
- src/media/local-audio-stream.ts
- src/mocks/create-permission-status.ts
- tsconfig.json
- yarn.lock
This PR updates the typescript version. It's needed to be able to use directly `RTCPeerConnectionIceErrorEvent` which is not available in current typescript version. 
Typescript options `suppressImplicitAnyIndexErrors` is getting deprecated. It's removal causes not being able to compile because `suppressLocalAudioPlayback` is not defined for `MediaTrackConstraints`. 
`suppressLocalAudioPlayback` is experimental, thus it's not in typescript yet.
Are we safe to remove this flag from constraints or we should add an typescript option which will supress deprecation of `suppressImplicitAnyIndexErrors`.
> feat: update typescript version

- src/peer-connection.ts
[SPARK-536950](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-536950)
This PR introduces forwarding of IceCandidateError event. We would like to be able to use it in JS-SDK to have a metrics about most common ice gathering issues.
With typescript update to version > 5.0, cast would not be needed.
> feat: expose icecandidateerror event

- package.json
- yarn.lock
web-media-effects versions above 2.18.1 require node 18+ and webrtc-core is not ready to upgrade node yet. This is a temporary fix to keep the web-media-effects lib at a version compatible with node 16 until we are ready to upgrade.
> fix: node effects lib compatible with node 16

- src/device/device-management.spec.ts
- src/device/device-management.ts
This PR introduces improvements and additions to the device management functionality, including conditional device permissions and unit tests. `getDevices()` function checks for all permissions irrespective of what the user has passed as `deviceKind`. This can cause unnecessary permission prompts for devices that aren't needed by the user.
This can be tested with: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-539683
> fix: conditionally add device permissions
